# syntax=docker/dockerfile:1
FROM docker.io/node:24-alpine AS frontend-builder

ARG MODULE
ARG FRONTEND_REF=main
ARG VITE_REMOTE_URL

RUN test -n "${MODULE}" || (echo "missing --build-arg=MODULE=<archeo|etno>" && exit 1)

WORKDIR /frontend
# hadolint ignore=DL3019
RUN --mount=type=cache,id=apk,target=/etc/apk/cache \
    apk add git=~2
RUN git clone --depth 1 --branch ${FRONTEND_REF} https://github.com/metafori-studio/collection-toolbox-frontend.git .

RUN --mount=type=cache,id=npm,target=/root/.npm \
    --mount=type=secret,id=mapbox_token \
    npm ci && \
    VITE_REMOTE_URL=${VITE_REMOTE_URL} VITE_MAPBOX_TOKEN=$(cat /run/secrets/mapbox_token) npm run build --workspace=apps/${MODULE}


FROM docker.io/composer:2.9.5 AS vendor-builder

WORKDIR /app
COPY . .
RUN --mount=type=cache,id=composer,target=/root/.composer/cache \
    composer install \
    --no-interaction \
    --no-dev \
    --prefer-dist \
    --optimize-autoloader \
    --no-scripts \
    --ignore-platform-req=php \
    --ignore-platform-req=ext-intl \
    --ignore-platform-req=ext-gd \
    --ignore-platform-req=ext-exif \
    --ignore-platform-req=ext-pgsql \
    --ignore-platform-req=ext-redis \
    --ignore-platform-req=ext-imagick


FROM docker.io/dunglas/frankenphp:1.12.1-php8.5

ARG MODULE
RUN test -n "${MODULE}" || (echo "ERROR: MODULE build arg is required (archeo or etno)" && exit 1)
ENV MODULE=${MODULE}

RUN --mount=type=cache,id=apt,sharing=locked,target=/var/cache/apt \
    --mount=type=cache,id=apt-lib,sharing=locked,target=/var/lib/apt \
    apt-get update && apt-get install -y --no-install-recommends \
        git \
        ghostscript \
        imagemagick

RUN --mount=type=cache,id=php-ext,target=/tmp/docker-php-extension-installer \
    install-php-extensions \
    pdo_pgsql \
    pgsql \
    redis \
    imagick \
    pcntl \
    intl \
    zip \
    opcache \
    curl

WORKDIR /app

COPY . .
RUN rm -rf bootstrap/cache/*.php

COPY --from=vendor-builder /app/vendor/ /app/vendor/
RUN php artisan package:discover --ansi \
    && php artisan modules:sync

COPY --from=frontend-builder /frontend/apps/${MODULE}/dist/ /app/public/

RUN php artisan octane:install --server=frankenphp

ENV OCTANE_SERVER=frankenphp

ENTRYPOINT ["php", "artisan", "octane:frankenphp"]
