# syntax=docker/dockerfile:1
FROM docker.io/node:24-alpine AS frontend-builder

ARG FRONTEND_REF=main
ARG BUILD_ENV=production

WORKDIR /frontend
# hadolint ignore=DL3019
RUN --mount=type=cache,id=apk,target=/etc/apk/cache \
    apk add git=~2 sops=~3.12 python3
RUN git clone --depth 1 --branch ${FRONTEND_REF} https://github.com/metafori-studio/collection-toolbox-frontend.git .

RUN --mount=type=cache,id=npm,target=/root/.npm \
    --mount=type=secret,id=sops_age_key \
    npm ci && \
    test -s /run/secrets/sops_age_key && \
    export SOPS_AGE_KEY_FILE=/run/secrets/sops_age_key && \
    ./scripts/build-ci.py archeo "${BUILD_ENV}"


FROM docker.io/composer:2.9.5 AS vendor-builder

WORKDIR /app
COPY app-modules /app-modules
COPY apps/archeo .
RUN --mount=type=cache,id=composer,target=/root/.composer/cache \
    composer install \
    --no-interaction \
    --no-dev \
    --prefer-dist \
    --optimize-autoloader \
    --no-scripts \
    --ignore-platform-req=php \
    --ignore-platform-req=ext-intl \
    --ignore-platform-req=ext-gd \
    --ignore-platform-req=ext-exif \
    --ignore-platform-req=ext-pgsql \
    --ignore-platform-req=ext-redis \
    --ignore-platform-req=ext-imagick


FROM docker.io/dunglas/frankenphp:1.12.1-php8.5

RUN --mount=type=cache,id=apt,sharing=locked,target=/var/cache/apt \
    --mount=type=cache,id=apt-lib,sharing=locked,target=/var/lib/apt \
    apt-get update && apt-get install -y --no-install-recommends \
        git \
        ghostscript \
        imagemagick \
        qpdf

RUN --mount=type=cache,id=php-ext,target=/tmp/docker-php-extension-installer \
    install-php-extensions \
    pdo_pgsql \
    pgsql \
    redis \
    imagick \
    pcntl \
    intl \
    zip \
    opcache \
    curl

WORKDIR /app

COPY app-modules /app-modules
COPY apps/archeo .

RUN rm -rf bootstrap/cache/*.php

COPY --from=vendor-builder /app/vendor/ vendor/

RUN php artisan package:discover --ansi

COPY --from=frontend-builder /frontend/apps/archeo/dist/ public/

RUN php artisan octane:install --server=frankenphp

ENV OCTANE_SERVER=frankenphp

ENTRYPOINT ["php", "artisan", "octane:frankenphp"]
