set shell := ["bash", "-c"]

default:
    @just --list

image_name := "ghcr.io/metafori-studio/collection-toolbox"

# Build the archeo image
build frontend_ref="main":
    podman build \
        --format docker \
        --build-arg=FRONTEND_REF={{frontend_ref}} \
        --secret id=mapbox_token,env=VITE_MAPBOX_TOKEN_ARCHEO \
        -f {{justfile_dir()}}/Containerfile \
        -t {{image_name}}:archeo-$(echo {{frontend_ref}} | sed 's|.*/||') \
        {{justfile_dir()}}/../../

# Push the archeo image
push frontend_ref="main":
    podman push {{image_name}}:archeo-$(echo {{frontend_ref}} | sed 's|.*/||')

# Build and push archeo
deploy frontend_ref="main":
    @just build {{frontend_ref}}
    @just push {{frontend_ref}}
