#!/bin/bash

BASE_URL="http://localhost:8000/api/archeo"

echo "--- List Activities (First Page, 5 per page, sorted by activity number) ---"
curl -s -X GET "${BASE_URL}/activities?per_page=5&sort=activity_number" -H "Accept: application/json" | jq

echo -e "\n\n--- List Activities (Filter by Activity Type) ---"
curl -s -G "${BASE_URL}/activities" \
    --data-urlencode "filter[activity_type][]=Research" \
    -H "Accept: application/json" | jq

echo -e "\n\n--- Get All Aggregations ---"
curl -s -X GET "${BASE_URL}/activities/aggregations" -H "Accept: application/json" | jq

echo -e "\n\n--- Get Filtered Aggregations (By District) ---"
curl -s -G "${BASE_URL}/activities/aggregations" \
    --data-urlencode "filter[district][]=Bratislava" \
    -H "Accept: application/json" | jq

echo -e "\n\n--- Show Specific Activity (By number) ---"
curl -s -X GET "${BASE_URL}/activities/31270" -H "Accept: application/json" | jq
