{
 "title": "SeaweedFS Dashboard",
 "tags": [
  "seaweedfs",
  "telemetry"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Total SeaweedFS Clusters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "seaweedfs_telemetry_total_clusters"
    }
   ]
  },
  {
   "title": "Active Clusters (7 days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "seaweedfs_telemetry_active_clusters"
    }
   ]
  },
  {
   "title": "SeaweedFS Version Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (version) (seaweedfs_telemetry_cluster_info)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Operating System Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (os) (seaweedfs_telemetry_cluster_info)",
     "legendFormat": "{{os}}"
    }
   ]
  },
  {
   "title": "Total Volume Servers Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(seaweedfs_telemetry_volume_servers)",
     "legendFormat": "Total Volume Servers"
    }
   ]
  },
  {
   "title": "Total Disk Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(seaweedfs_telemetry_disk_bytes)",
     "legendFormat": "Total Disk Usage"
    }
   ]
  },
  {
   "title": "Total Volume Count Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(seaweedfs_telemetry_volume_count)",
     "legendFormat": "Total Volume Count"
    }
   ]
  },
  {
   "title": "Total Filer Servers Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(seaweedfs_telemetry_filer_count)",
     "legendFormat": "Total Filer Count"
    }
   ]
  },
  {
   "title": "Total Broker Servers Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(seaweedfs_telemetry_broker_count)",
     "legendFormat": "Total Broker Count"
    }
   ]
  }
 ]
}