set shell := ["bash", "-c"]

default:
    @just --list

image_name := "ghcr.io/metafori-studio/collection-toolbox"

build frontend_ref="main" build_env="development" age_key=env_var('SOPS_AGE_KEY_FILE'):
    podman build \
        --format docker \
        --build-arg=FRONTEND_REF={{frontend_ref}} \
        --build-arg=BUILD_ENV={{build_env}} \
        --secret id=sops_age_key,src={{age_key}} \
        -f {{justfile_dir()}}/Containerfile \
        -t {{image_name}}:etno-$(echo {{frontend_ref}} | sed 's|.*/||') \
        {{justfile_dir()}}/../../

push frontend_ref="main":
    podman push {{image_name}}:etno-$(echo {{frontend_ref}} | sed 's|.*/||')

deploy frontend_ref="main" build_env="development" age_key=env_var('SOPS_AGE_KEY_FILE'):
    @just build {{frontend_ref}} {{build_env}} {{age_key}}
    @just push {{frontend_ref}}
