name: CI

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Install Nix
      uses: determinateSystems/nix-installer-action@v16

    - name: Magic Nix Cache
      uses: determinateSystems/magic-nix-cache-action@v8

    - name: Install Dependencies
      run: nix develop --command composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Copy .env
      run: nix develop --command php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate App Key
      run: nix develop --command php artisan key:generate

    - name: Run Pint
      run: nix develop --command ./vendor/bin/pint --test

    - name: Run Larastan
      run: nix develop --command ./vendor/bin/phpstan analyse --no-progress

    - name: Run Tests
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: collection_toolbox_backend
        DB_USERNAME: postgres
        DB_PASSWORD: ''
      run: nix develop --command php artisan test
